/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MenuActionActiveEvent } from "./components/dynamic-menu-action/dynamic-menu-action";
export namespace Components {
    interface DynamicMenu {
        /**
          * A CSS class to set as the `dynamic-menu` element class.
         */
        "cssClass": string;
    }
    interface DynamicMenuAction {
        /**
          * This attribute lets you specify if the menu action is activated
         */
        "active": boolean;
        /**
          * A CSS class to set as the `dynamic-menu-action` element class when `active = true`.
         */
        "activeClass": string;
        /**
          * A CSS class to set as the `dynamic-menu-action` element class.
         */
        "cssClass": string;
        /**
          * The subtitle of menu action.
         */
        "itemSubtitle": string;
        /**
          * The title of menu action.
         */
        "itemTitle": string;
        /**
          * This attribute specifies which popup of the dynamic-menu must be open.
         */
        "popupId": string;
    }
    interface DynamicMenuPopup {
        /**
          * A CSS class to set as the `dynamic-menu-popup` element class.
         */
        "cssClass": string;
        /**
          * This attribute lets you specify if the menu popup is opened
         */
        "opened": boolean;
    }
}
export interface DynamicMenuActionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDynamicMenuActionElement;
}
declare global {
    interface HTMLDynamicMenuElement extends Components.DynamicMenu, HTMLStencilElement {
    }
    var HTMLDynamicMenuElement: {
        prototype: HTMLDynamicMenuElement;
        new (): HTMLDynamicMenuElement;
    };
    interface HTMLDynamicMenuActionElement extends Components.DynamicMenuAction, HTMLStencilElement {
    }
    var HTMLDynamicMenuActionElement: {
        prototype: HTMLDynamicMenuActionElement;
        new (): HTMLDynamicMenuActionElement;
    };
    interface HTMLDynamicMenuPopupElement extends Components.DynamicMenuPopup, HTMLStencilElement {
    }
    var HTMLDynamicMenuPopupElement: {
        prototype: HTMLDynamicMenuPopupElement;
        new (): HTMLDynamicMenuPopupElement;
    };
    interface HTMLElementTagNameMap {
        "dynamic-menu": HTMLDynamicMenuElement;
        "dynamic-menu-action": HTMLDynamicMenuActionElement;
        "dynamic-menu-popup": HTMLDynamicMenuPopupElement;
    }
}
declare namespace LocalJSX {
    interface DynamicMenu {
        /**
          * A CSS class to set as the `dynamic-menu` element class.
         */
        "cssClass"?: string;
    }
    interface DynamicMenuAction {
        /**
          * This attribute lets you specify if the menu action is activated
         */
        "active"?: boolean;
        /**
          * A CSS class to set as the `dynamic-menu-action` element class when `active = true`.
         */
        "activeClass"?: string;
        /**
          * A CSS class to set as the `dynamic-menu-action` element class.
         */
        "cssClass"?: string;
        /**
          * The subtitle of menu action.
         */
        "itemSubtitle"?: string;
        /**
          * The title of menu action.
         */
        "itemTitle"?: string;
        /**
          * Fired when the menu action is activated.
         */
        "onMenuActionActivated"?: (event: DynamicMenuActionCustomEvent<MenuActionActiveEvent>) => void;
        /**
          * Fired when a KeyboardEvent is captured for the menu action.
         */
        "onMenuActionKeyDown"?: (event: DynamicMenuActionCustomEvent<KeyboardEvent>) => void;
        /**
          * This attribute specifies which popup of the dynamic-menu must be open.
         */
        "popupId"?: string;
    }
    interface DynamicMenuPopup {
        /**
          * A CSS class to set as the `dynamic-menu-popup` element class.
         */
        "cssClass"?: string;
        /**
          * This attribute lets you specify if the menu popup is opened
         */
        "opened"?: boolean;
    }
    interface IntrinsicElements {
        "dynamic-menu": DynamicMenu;
        "dynamic-menu-action": DynamicMenuAction;
        "dynamic-menu-popup": DynamicMenuPopup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dynamic-menu": LocalJSX.DynamicMenu & JSXBase.HTMLAttributes<HTMLDynamicMenuElement>;
            "dynamic-menu-action": LocalJSX.DynamicMenuAction & JSXBase.HTMLAttributes<HTMLDynamicMenuActionElement>;
            "dynamic-menu-popup": LocalJSX.DynamicMenuPopup & JSXBase.HTMLAttributes<HTMLDynamicMenuPopupElement>;
        }
    }
}
